# Generated by Django 5.1.4 on 2024-12-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0002_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allotments.section'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allotments.branch'),
        ),
    ]
