# Generated by Django 5.1.4 on 2025-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0003_subject_section_alter_subject_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='no_of_classes',
            field=models.IntegerField(null=True),
        ),
    ]
