# Generated by Django 5.1.4 on 2025-01-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0005_class_room_alter_subject_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students_in_class',
            field=models.CharField(choices=[('boys', 'Only Boys'), ('girls', 'Only Girls'), ('combine', 'Combine')], default='combine', max_length=10),
        ),
    ]
