# Generated by Django 5.1.4 on 2025-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0006_subject_students_in_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Type_of_class',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='Theory', max_length=10),
        ),
    ]
