# Generated by Django 5.1.4 on 2025-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0007_subject_type_of_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_room',
            name='Faculty_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
