# Generated by Django 5.1.4 on 2025-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0009_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
