# Generated by Django 5.1.4 on 2025-01-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0011_timetable_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
