# Generated by Django 5.1.4 on 2025-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0013_alter_timetable_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='code',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='allotments.teacher'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='allotments.teacher'),
        ),
    ]
