# Generated by Django 5.1.4 on 2025-03-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0014_remove_subject_teacher_remove_timetable_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teachers',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
