# Generated by Django 5.1.4 on 2025-03-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0016_faculty_alter_class_room_faculty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_room',
            name='Faculty_name',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
